"""Initial migration

Revision ID: 6755a05b4dbd
Revises: 07453c7f0d1b
Create Date: 2025-12-12 23:33:09.759913

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '6755a05b4dbd'
down_revision: Union[str, Sequence[str], None] = '07453c7f0d1b'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user_communities', sa.Column('id', sa.Integer(), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('user_communities', 'id')
    # ### end Alembic commands ###
