"""add reactions_data column to comments table

Revision ID: 80a5f95d4473
Revises: 4670640018b9
Create Date: 2025-12-19 02:37:24.008874

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '80a5f95d4473'
down_revision: Union[str, Sequence[str], None] = '4670640018b9'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('comments', sa.Column('reactions_data', sa.Text(), nullable=True, server_default='{"liked_by": [], "disliked_by": []}'))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('comments', 'reactions_data')
    # ### end Alembic commands ###
