"""add_image_column_to_communities

Revision ID: fcbc927b3e79
Revises: 46209a0a1870
Create Date: 2025-12-17 16:45:07.366968

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'fcbc927b3e79'
down_revision: Union[str, Sequence[str], None] = '46209a0a1870'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # Add image column to communities table
    op.add_column('communities', sa.Column('image', sa.String(length=255), nullable=True))


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('communities', 'image')
    op.create_table('reports',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('reporter_id', sa.INTEGER(), nullable=False),
    sa.Column('content_type', sa.VARCHAR(length=7), nullable=False),
    sa.Column('content_id', sa.INTEGER(), nullable=False),
    sa.Column('reason', sa.TEXT(), nullable=False),
    sa.Column('description', sa.TEXT(), nullable=True),
    sa.Column('status', sa.VARCHAR(length=8), nullable=False),
    sa.Column('created_at', sa.DATETIME(), nullable=False),
    sa.Column('updated_at', sa.DATETIME(), nullable=False),
    sa.Column('moderator_id', sa.INTEGER(), nullable=True),
    sa.Column('moderator_comment', sa.TEXT(), nullable=True),
    sa.ForeignKeyConstraint(['moderator_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['reporter_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###
